name: Docker Re-tag

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  retag-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Re-tag production image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          # Pull latest production image
          docker pull ${{ env.REGISTRY }}/$REPO_NAME:latest
          
          # Re-tag as dev
          docker tag ${{ env.REGISTRY }}/$REPO_NAME:latest ${{ env.REGISTRY }}/$REPO_NAME:dev
          
          # Push dev-tagged image
          docker push ${{ env.REGISTRY }}/$REPO_NAME:dev